import type { Metadata } from "next";
import "./globals.css";
import AuthProvider from "./providers/AppProviders";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full overflow-hidden">
      <body className={`antialiased h-full overflow-hidden`}>
        <AuthProvider>{children}</AuthProvider> 
     {/*    {children} */}
      </body>
    </html>
  );
}
